version: "3.8"

services:
  mkdocs-builder:
    container_name: mkdocs-builder
    build:
      context: .
      dockerfile: Dockerfile
      args:
        progress: plain
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/app
    working_dir: /app
    entrypoint: ["python", "-m", "mkdocs", "build"]
