version: "3.8"

services:
  mkdocs-builder:
    container_name: mkdocs-builder
    build:
      context: .
      dockerfile: Dockerfile
#      target: installe
      args:
        progress: plain
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/app
#    working_dir: /app
#    entrypoint:
#      - "ls -al"

#services:
#  plantuml:
#    container_name: plantuml
#    image: plantuml/plantuml-server:jetty
#    ports:
#      - "9080:8080"
#  mkdocs-builder:
#    container_name: mkdocs-builder
#    image: python:3.12.0-alpine
#    stdin_open: true
#    tty: true
#    volumes:
#      - ${PWD}:/app
#    entrypoint: ["sh", "-c"]
#    working_dir: /app
#    command:
#      - |
#        ls -al
#        pip install --no-cache-dir -r requirements.txt
#    entrypoint:
#      - "ls -al"
