version: "3.8"

services:
  plantuml-server:
    container_name: plantuml-server
    image: plantuml/plantuml-server:jetty
    stdin_open: true
    tty: true
    networks:
      - proxy
    expose:
      - "8080"
    ports:
      - "8090:8080"

#  mkdocs-builder:
#    container_name: mkdocs-builder
#    image: python:3.12.0
#    stdin_open: true
#    tty: true
#    networks:
#      - proxy
#    depends_on:
#      - plantuml-server
#    environment:
#      - PLANT_UML_SERVER=http://plantuml-server:8080/
##    expose:
##      - "8000"
#    ports:
#      - "8000:8000"
#    volumes:
#      - ${PWD}:/app
#    working_dir: /app
#    #curl -sSfL http://plantuml-server:8080
#    command:
#      - /bin/sh
#      - -c
#      - |
#        pip install -r requirements.txt
#        python -m mkdocs ${COMMAND}

networks:
  proxy:
